#!/bin/bash

echo "Removing hack installation..."

echo "Requesting sudo permissions... (you may be prompted for your password)"
sudo -v

read -p "Are you sure you want to uninstall hack? [y/n]: " confirm
if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
    sudo rm -f $(which hack)
    sudo rm -f $(which hackUpdater)
    sudo rm -f $(which hackUninstaller)
    echo "Hack uninstalled successfully."
else
    echo "Uninstallation cancelled."
fi

read -p "#Would you like to restart your terminal now to apply changes? (y/n): " restart_terminal
if [ "$restart_terminal" = "y" ] || [ "$restart_terminal" = "Y" ]; then
    source ~/.bash_profile 2>/dev/null || source ~/.zshrc 2>/dev/null
    clear
    hack -h
fi